# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: "resources/.*|docs/make.bat"
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: "docs/make.bat"
    -   id: check-added-large-files
        args: ['--maxkb=1000']

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.0
    hooks:
    -   id: ruff
        args: ['--fix']

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:

    - id: pyupgrade
      name: pyupgrade-general
      args: [--py311-plus]
      exclude: ^pysec/cli/  # skip `cli/` directory

    - id: pyupgrade
      name: pyupgrade-cli-conservative
      args: [--py38-plus]  # to keep Optional[]
      files: ^pysec/cli/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.0'
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        files: ^pysec/.*
