[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pysec"
version = "0.1.0"
description = "FOSS Endpoint Security"
authors = [{ name = "Martin Thoma", email = "info@martin-thoma.de" }]
dependencies = [
    "rich",
    "requests",
    "typer[all]",
    "appdirs",
]

[project.scripts]
pysec = "pysec.cli:main"


[tool.flit.sdist]
exclude = ["tests/", "*.pyc", "__pycache__"]


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A004",  # Import `print` is shadowing a Python builtin
    "BLE001",  # Do not catch blind exception: `Exception`
    "D101", #  Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D104", #  Missing docstring in public package
    "D203",  # `incorrect-blank-line-before-class`
    "D212",    # I want multiline-docstrings to start at the second line
    "FA102",  # Missing `from __future__ import annotations`, but uses PEP 604 union
    "PERF203", # `try`-`except` within a loop incurs performance overhead
    "PLW2901",  # `for` loop variable `line` overwritten by assignment target
    "S110",  # `try`-`except`-`pass` detected, consider logging the exception
    "S112", # `try`-`except`-`continue` detected, consider logging the exception
    "S603",  # `subprocess` call: check for execution of untrusted input
    "S607",  # Starting a process with a partial executable path

]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "INP001",
    "D103", # Missing docstring in public function
    "S101",  # Use of `assert` detected
    ]
