# Generated by Django 5.1.4 on 2025-07-06 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS security_info (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                client_id INTEGER NOT NULL,
                disk_encrypted BOOLEAN,
                screen_lock_timeout INTEGER,
                auto_updates_enabled BOOLEAN,
                os_checker_available BOOLEAN DEFAULT 0,
                error TEXT,
                submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                os_version TEXT,
                kernel_version TEXT,
                architecture TEXT,
                security_updates_count INTEGER DEFAULT 0
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS security_info;",
        ),
    ]
