# Generated by Django 5.2.4 on 2025-07-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="package_repository",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown/Legacy"),
                    ("DEBIAN_APT", "Debian/Ubuntu APT"),
                    ("PYTHON_PIP", "Python pip"),
                    ("SNAP", "Snap packages"),
                    ("HOMEBREW", "Homebrew (macOS)"),
                    ("ARCH_PACMAN", "Arch Linux Pacman"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
