# Generated by Django 5.1.4 on 2025-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_package_package_repository"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_repository",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown/Legacy"),
                    ("DEBIAN_APT", "Debian/Ubuntu APT"),
                    ("PYTHON_PIP", "Python pip"),
                    ("SNAP", "Snap packages"),
                    ("HOMEBREW", "Homebrew (macOS)"),
                    ("ARCH_PACMAN", "Arch Linux Pacman"),
                    ("DOCKER", "Docker images/containers"),
                ],
                max_length=20,
            ),
        ),
    ]
