# Generated by Django 5.1.4 on 2025-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_auto_20250706_0724"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="securityinfo",
            options={"ordering": ("-submitted_at",)},
        ),
        migrations.AlterField(
            model_name="client",
            name="token",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
